# Generated by Django 5.2.4 on 2025-08-07 22:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='O nome completo do fornecedor.', max_length=255, verbose_name='Nome do Fornecedor')),
                ('contact_person', models.CharField(blank=True, help_text='O nome da pessoa de contato na empresa do fornecedor.', max_length=255, null=True, verbose_name='Pessoa de Contato')),
                ('cnpj', models.CharField(help_text='Número de Cadastro Nacional da Pessoa Jurídica.', max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('phone', models.CharField(help_text='Número de telefone para contato.', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Endereço de email para contato.', max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(help_text='Endereço completo do fornecedor.', max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(help_text='Sigla do estado (ex: SP, RJ).', max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, help_text='Código de Endereçamento Postal.', max_length=10, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('active', models.BooleanField(default=True, help_text='Indica se o fornecedor está ativo no sistema.', verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.company')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
    ]
