# Generated by Django 5.2.4 on 2025-08-13 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0002_alter_product_id'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número da Nota')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total da Nota')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('FINALIZED', 'Finalizada'), ('CANCELED', 'Cancelada')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.company', verbose_name='Empresa')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota de Compra',
                'verbose_name_plural': 'Notas de Compra',
                'unique_together': {('company', 'supplier', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='PayableAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga'), ('OVERDUE', 'Vencida')], default='PENDING', max_length=10, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='core.company', verbose_name='Empresa')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='purchases.purchaseinvoice', verbose_name='Nota de Origem')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo Total do Item')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice', verbose_name='Nota de Compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produto')),
            ],
        ),
    ]
